use_frameworks!
inhibit_all_warnings!

project 'KSNTwitterFeed'

use_frameworks!

def shared_pods
    # Private pods (from KSNTwitterFeed.podspec)
    pod 'KSNObservable', :path => '../Development Pods/KSNObservable'
    pod 'KSNErrorHandler', :path => '../Development Pods/KSNErrorHandler'
    pod 'KSNDataSource', :path => '../Development Pods/KSNDataSource'
    pod 'KSNUtils', :path => '../Development Pods/KSNUtils'
    # Changed pods
    pod 'AFMInfoBanner', :path => '../Development Pods/AFMInfoBanner'
    
    # Public pods
    pod 'JRSwizzle' # I'm sorry mama. I'm trying to avoid method swizzling as much as I can. (One place where I can't avoid it - NSObject+KSNModal)
    pod 'CocoaLumberjack'
    pod 'MagicalRecord' # I don't like this pod, but it's not a right place to come up with self-made velosiped :)
    pod 'Masonry'
    pod 'AsyncDisplayKit'
end

target 'KSNTwitterFeed_Example' do
    shared_pods
    pod 'KSNTwitterFeed', :path => '../'
    
    target 'KSNTwitterFeed_Tests' do
        inherit! :search_paths
        
        pod 'Kiwi'
        pod 'OCMock', '~> 3.1.2'
    end
end

post_install do |installer|
    
    FileUtils.cp_r('./Pods/Target Support Files/Pods-KSNTwitterFeed_Example/Pods-KSNTwitterFeed_Example-acknowledgements.plist', './Settings.bundle/Acknowledgements.plist', :remove_destination => true)
    
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['DEBUG_INFORMATION_FORMAT'] = "dwarf-with-dsym"
        end
    end
end





